version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_dev
    ports:
      - "5432:5432"
    restart: unless-stopped 

volumes:
  postgres-data:
